Repository cryptoeconomicslab/plasma-rust-framework, pull requests merged in 2019-07, with the labels that each got.

#100 Remove unnecessary SyncManagerTrait #98
  client/src/sync/sync_manager.rs
Labels: clean

#108 Remove SyncDbTrait #105
  client/src/sync/sync_db.rs
  client/src/sync/sync_manager.rs
Labels: clean

#107 Follow the latest data structures #106 #80
  Cargo.lock
  client/src/plasma_rpc.rs
  client/src/state/state_db.rs
  client/src/state/state_manager.rs
  client/src/sync/sync_db.rs
  core/Cargo.toml
  core/src/data_structure.rs
  core/src/data_structure/abi.rs
  core/src/data_structure/range.rs
  core/src/data_structure/state_object.rs
  core/src/data_structure/state_query.rs
  core/src/data_structure/state_update.rs
  core/src/data_structure/transaction.rs
  operator/src/block/block_db.rs
  operator/src/context.rs
  operator/src/rpc/plasmarpcimpl.rs
  predicate-plugins/src/ownership.rs
  wasm/src/lib.rs
Labels: bug

#113 Add minimal contract wrapper
  Cargo.lock
  Cargo.toml
  contract-wrapper/Cargo.toml
  contract-wrapper/CommitmentChain.json
  contract-wrapper/Deposit.json
  contract-wrapper/src/contract_wrapper.rs
  contract-wrapper/src/lib.rs
  contract-wrapper/src/main.rs
Labels: enhancement

#111 Remove generics of output type from KeyValueStore #105
  client/src/state/state_db.rs
  client/src/state/state_manager.rs
  client/src/sync/sync_db.rs
  client/src/sync/sync_manager.rs
  db/src/impls/kvs/leveldb.rs
  db/src/impls/kvs/memory.rs
  db/src/impls/rangedb.rs
  db/src/traits/kvs.rs
  event-watcher/src/event_db.rs
  operator/src/block/block_db.rs
  operator/src/block/block_manager.rs
Labels: clean

#122 Fix warnnings #112
  client/src/error.rs
  core/src/data_structure/error.rs
  operator/src/error.rs
Labels: clean
